apiVersion: v1
kind: Service
metadata:
  name: techpathway-warehouse
  labels:
    app: techpathway-warehouse
spec:
  type: ClusterIP
  selector:
    app: techpathway-warehouse
  ports:
    - port: 5002
      targetPort: 5002