apiVersion: v1
kind: ConfigMap
metadata:
  name: main-app-config
data:
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  NOTIFICATION_SERVICE_URL: "http://action-messages:5001"
  WAREHOUSE_SERVICE_URL: "http://techpathway-warehouse:5002"
  NOTIFICATION_PUBLIC_URL: "http://localhost:5001"
  WAREHOUSE_PUBLIC_URL: "http://localhost:5002"